# ----------- CONFIGURABLE START -----------
title:            "Alex Kai的博客"
description:      "即将步入社会|我想追求的生活是社么样呢|我想成为什么样的人呢"
url:              "https://alexkaiqi.github.io/" # 域名
baseurl: ""
signoff:          "Alex Kai" # Your name
email:            alexkaiqi@gmail.com


#google_analytics:
share:            true
kramdown:
  input: GFM
# 分页
paginate: 15
paginate_path: "alexkaiqipage:num"
plugins: [jekyll-paginate]
include: ['_pages']
# ------------ CONFIGURABLE END ------------


links:
  - name:         首页
    url:          /
    external:     false
  - name:         书籍
    url:          /book
    external:     false
  - name:         旅游
    url:          /road
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false


#defaults:
defaults:
  -
    scope:
      path: "_posts"
      types: "posts"
    values:
      layout: "blog"
      permalink: /:year/:month/:day/:title.html
  -
    scope:
      path: "_pages"
      types: "pages"
    values:
      layout: "default"
      author: "Alex Kai"
      permalink: /:category/

#social links
facebook_appid:   #facebook_id
github_username:  alexkaiqi
github_url: https://github.com/alexkaiqi
twitter_username: alexkaiqi
twitter_url: https://twitter.com/alexkaiqi
stackoverflow_username: alex-kai
stackoverflow_url: https://stackoverflow.com/users/7967346/alex-kai
social:
  - name: facebook
    url:
    username: alexkaiqi
  - name: twitter
    url: https://twitter.com/alexkaiqi
    username: alexkaiqi
  - name: github
    url: https://github.com/alexkaiqi
    username: alexkaiqi
  - name: stackoverflow
    url: https://stackoverflow.com/users/7967346/alex-kai
    username: alex-kai
